# Generated by Django 5.1 on 2025-08-14 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_productimage_image_alter_roomimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='label',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
    ]
