# Generated by Django 5.1 on 2025-08-16 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_product_label_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='SubCategory',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='room',
            new_name='sub_category',
        ),
        migrations.AddField(
            model_name='category',
            name='sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.subcategory'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RoomImage',
        ),
    ]
