# Generated by Django 5.1 on 2025-08-16 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_room_subcategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='sub_category',
            new_name='subcategory',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sub_category',
            new_name='subcategory',
        ),
    ]
