# Generated by Django 5.1 on 2025-08-16 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_subcategory_category_category_sub_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='quote',
        ),
    ]
