# Generated by Django 5.1 on 2025-08-18 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_subcategory_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sort',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
