# Generated by Django 5.1 on 2025-08-18 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='sub_categories',
            new_name='subcategories',
        ),
    ]
